services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev

  backend:
    build: ./backend
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_ENV=dev
      - DATABASE_URL=sqlsrv://sa:YourStrong!Passw0rd@database:1433/stackoverflow

  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    volumes:
      - ./database/data:/var/opt/mssql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "1433:1433"

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

volumes:
  caddy_data:
  caddy_config: